- hosts: localhost
  connection: local
  tasks:
    - name: enable and start dhcpcd for network connection
      systemd:
        name: dhcpcd
        enabled: yes
        state: started

    - name: install arch packages
      become: yes
      package: name={{item}}
      with_items:
        - fzf
        - firefox
        - chromium
        - htop
        - git
        - sway
        - zsh

    - name: install aur packages
      aur: name="{{ item }}" state=latest aur_only=yes use=yay
      with_items:
        - neovim-nightly-bin
        - termite-nocsd

