- hosts: localhost
  connection: local
  tasks:
    - name: enable and start dhcpcd for network connection
      become: yes
      systemd:
        name: dhcpcd
        enabled: yes
        state: started

    - name: install arch packages
      become: yes
      package: name={{item}}
      with_items:
        - bemenu-wlroots
        - chromium
        - firefox
        - fzf
        - htop
        - interception-caps2esc
        - git
        - sway
        - zsh

    - name: install aur packages
      aur: name="{{ item }}" state=latest aur_only=yes use=yay
      with_items:
        - neovim-nightly-bin
        - termite-nocsd

    - name: create caps2esc interception tools file
      become: yes
      blockinfile:
        create: yes
        path: /etc/interception/udevmon.yaml
        block: |
          - JOB: intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE
            DEVICE:
              EVENTS:
                EV_KEY: [KEY_CAPSLOCK, KEY_ESC]

    - name: enable and start udevmon interception for caps2esc
      become: yes
      systemd:
        name: udevmon
        enabled: yes
        state: started
