- hosts: localhost
  connection: local
  tasks:
    - name: install arch packages
      become: yes
      package: name={{item}}
      with_items:
        - htop
        - sway
        - termite

    - name: install aur packages
      aur: name="{{ item }}" state=latest aur_only=yes use=yay
      with_items:
        - neovim-nightly-bin

    - name: enable and start dhcpcd for network connection
      systemd:
        name: dhcpcd
        enabled: yes
        state: started
