- hosts: localhost
  connection: local
  tasks:
    - name: aur plugin installation
      git:
        repo: 'https://github.com/kewlfft/ansible-aur.git'
        dest: '~/.ansible/plugins/modules/aur'
